auth_enabled: false

server:
  grpc_server_max_recv_msg_size: 6194304

common:
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: inmemory
  replication_factor: 1
  path_prefix: /alloc/data/loki

schema_config:
  configs:
  - from: 2024-05-15
    store: tsdb
    object_store: filesystem
    schema: v13
    index:
      prefix: index_
      period: 24h

storage_config:
  filesystem:
    directory: /alloc/data/loki/chunks

table_manager:
  retention_deletes_enabled: true
  retention_period: 24h
