global:
  scrape_interval: "15s"

scrape_configs:
  - job_name: "traefik"
    consul_sd_configs:
      - server: http://127.0.0.1:8500
        services:
          - "traefik"
    relabel_configs:
      - source_labels: ["__meta_consul_node"]
        target_label: "instance"
      - source_labels: ["__address__"]
        target_label: "env"
        replacement: "dev"

  - job_name: "cometbft"
    consul_sd_configs:
      - server: http://127.0.0.1:8500
        services:
          - "cometbft-metrics"
    relabel_configs:
      - source_labels: ["__meta_consul_service_metadata_instance"]
        target_label: "instance"
      - source_labels: ["__address__"]
        target_label: "env"
        replacement: "dev"

  - job_name: "fendermint"
    consul_sd_configs:
      - server: http://127.0.0.1:8500
        services:
          - "fendermint-metrics"
    relabel_configs:
      - source_labels: ["__meta_consul_service_metadata_instance"]
        target_label: "instance"
      - source_labels: ["__address__"]
        target_label: "env"
        replacement: "dev"

  - job_name: "consul-connect-envoy"
    consul_sd_configs:
      - server: http://127.0.0.1:8500
    relabel_configs:
      - source_labels: ["__meta_consul_service"]
        action: "drop"
        regex: "(.+)-sidecar-proxy"
      - source_labels: ["__meta_consul_service_metadata_envoy"]
        action: "keep"
        regex: "(.+)"
      - source_labels: ["__address__", "__meta_consul_service_metadata_envoy"]
        regex: '([^:]+)(?::\d+)?;(\d+)'
        replacement: "${1}:${2}"
        target_label: "__address__"
      - source_labels: ["__address__"]
        target_label: "env"
        replacement: "dev"
