global:
  scrape_interval: "15s"
  external_labels:
    env: "dev"

remote_write:
  - url: "http://mimir.service.consul:9898/api/v1/push"

scrape_configs:
  - job_name: "traefik"
    consul_sd_configs:
      - server: http://127.0.0.1:8500
        datacenter: "${WORKSPACE}"
        services:
          - "traefik"
    relabel_configs:
      - source_labels: ["__meta_consul_node"]
        target_label: "instance"

  - job_name: "cometbft"
    consul_sd_configs:
      - server: http://127.0.0.1:8500
        datacenter: "${WORKSPACE}"
        services:
          - "cometbft-metrics"
    relabel_configs:
      - source_labels: ["__meta_consul_service_metadata_instance"]
        target_label: "instance"

  - job_name: "fendermint"
    consul_sd_configs:
      - server: http://127.0.0.1:8500
        datacenter: "${WORKSPACE}"
        services:
          - "fendermint-metrics"
    relabel_configs:
      - source_labels: ["__meta_consul_service_metadata_instance"]
        target_label: "instance"

  - job_name: "consul-connect-envoy"
    consul_sd_configs:
      - server: http://127.0.0.1:8500
        datacenter: "${WORKSPACE}"
    relabel_configs:
      - source_labels: ["__meta_consul_service"]
        action: "drop"
        regex: "(.+)-sidecar-proxy"
      - source_labels: ["__meta_consul_service_metadata_envoy"]
        action: "keep"
        regex: "(.+)"
      - source_labels: ["__address__", "__meta_consul_service_metadata_envoy"]
        regex: '([^:]+)(?::\d+)?;(\d+)'
        replacement: "${1}:${2}"
        target_label: "__address__"
