data_dir: '/alloc/data'

api:
  enabled: false
  address: '0.0.0.0:2080'
  playground: true

sources:
  cometbft_logs:
    type: "file"
    include:
      - "/alloc/logs/cometbft.*"

  fendermint_logs:
    type: "file"
    include:
      - "/alloc/logs/fendermint.*"

sinks:
  s3_cometbft:
    auth:
      access_key_id: "admin"
      secret_access_key: "admin"
    inputs:
      - "cometbft_logs"
    type: "aws_s3"
    region: "us-east-2"
    bucket: "logs"
    endpoint: "http://seaweedfs-filer.service.consul:9534"
    key_prefix: "ipc/${INDEX}/cometbft/"
    compression: "none"
    framing:
      method: "newline_delimited"
    encoding:
      codec: "text"
    filename_append_uuid: false
    filename_time_format: "%+"
    healthcheck:
      enabled: false

  s3_fendermint:
    auth:
      access_key_id: "admin"
      secret_access_key: "admin"
    inputs:
      - "fendermint_logs"
    type: "aws_s3"
    region: "us-east-2"
    bucket: "logs"
    endpoint: "http://seaweedfs-filer.service.consul:9534"
    key_prefix: "ipc/${INDEX}/fendermint/"
    compression: "none"
    framing:
      method: "newline_delimited"
    encoding:
      codec: "text"
    filename_append_uuid: false
    filename_time_format: "%+"
    healthcheck:
      enabled: false
