server:
  http_listen_port: ${NOMAD_PORT_promtail}

positions:
  filename: "${NOMAD_ALLOC_DIR}/data/positions.yml"

clients:
  - url: "http://127.0.0.1:8000" # TODO

scrape_configs:
  - job_name: "traefik"
    static_configs:
    - labels:
        source: "traefik"
        instance: "${NOMAD_NODE_NAME}"
        __path__: "${NOMAD_ALLOC_DIR}/data/access.log"
    pipeline_stages:
      - json:
          expressions:
            time: time
            level: level
            method: RequestMethod
            status: DownstreamStatus
            service: ServiceName
            path: RequestPath
      - labels:
          service:
      - timestamp:
          source: time
          format: "RFC3339"
      - drop:
          source: path
          expression: "/ping"
      - drop:
          source: path
          expression: "/metrics"
