multitenancy_enabled: true

target: all

tenant_federation:
  enabled: true

common:
  storage:
    backend: s3
    s3:
      endpoint: seaweedfs-filer.service.consul:9534
      region: us-east-2
      secret_access_key: "admin"
      access_key_id: "admin"
      insecure: true

blocks_storage:
  s3:
    bucket_name: mimir
  bucket_store:
    sync_dir: /alloc/data/tsdb-sync
  tsdb:
    dir: /alloc/data/tsdb
    flush_blocks_on_shutdown: true

compactor:
  data_dir: /alloc/data/compactor
  sharding_ring:
    kvstore:
      store: memberlist

distributor:
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: memberlist

ingester:
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: memberlist
    replication_factor: 1

ruler_storage:
  backend: filesystem
  filesystem:
    dir: /alloc/data/rules
