scope: postgres

bootstrap:
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    maximum_lag_on_failover: 1048576
    postgresql:
      parameters:
        wal_keep_segments: 32
      pg_hba:
        - "local all all trust"
        - "host all all 0.0.0.0/0 md5"
        - "host replication repl 0.0.0.0/0 md5"
        - "host replication repl 0.0.0.0/0 password"

  initdb:
    - encoding: UTF8
    - data-checksums

restapi:
  listen: 0.0.0.0:8043

consul:
  host: 127.0.0.1
  port: 8500
  register_service: true

postgresql:
  listen: "0.0.0.0:5432"
  data_dir: "/data/patroni/postgres"
