global:
  scrape_interval: "15s"
  external_labels:
    env: "dev"

scrape_configs:
  - job_name: "traefik"
    consul_sd_configs:
      - server: http://127.0.0.1:8500
        services:
          - "traefik"
    relabel_configs:
      - source_labels: ["__meta_consul_node"]
        target_label: "instance"

  - job_name: "cometbft"
    consul_sd_configs:
      - server: http://127.0.0.1:8500
        services:
          - "cometbft-metrics"
    relabel_configs:
      - source_labels: ["__meta_consul_service_metadata_instance"]
        target_label: "instance"

  - job_name: "fendermint"
    consul_sd_configs:
      - server: http://127.0.0.1:8500
        services:
          - "fendermint-metrics"
    relabel_configs:
      - source_labels: ["__meta_consul_service_metadata_instance"]
        target_label: "instance"
