name: cleanup dev env

on:
  pull_request:
    types: [ closed ]
    branches:
      - "main"

jobs:
  prepare:
    runs-on: ubuntu-latest

    outputs:
      jobs: "${{ steps.jobs.outputs.jobs }}"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create matrix with jobs
        id: jobs
        run: |
          # create matrix with jobs
          jobs=$(find dev-env/jobs/* -maxdepth 0 -type d  | jq -R . | jq -sc .)
          echo "jobs=${jobs}" >> $GITHUB_OUTPUT

  jobs:
    needs:
      - prepare

    uses: ./.github/workflows/terraform.yml
    with:
      workspace: "${{ github.repository_id }}-${{ github.event.pull_request.number }}"
      matrix: "${{ needs.prepare.outputs.jobs }}"
      destroy: true

  instances:
    needs:
      - jobs

    uses: ./.github/workflows/terraform.yml
    with:
      matrix: '["dev-env"]'
      workspace: "${{ github.repository_id }}-${{ github.event.pull_request.number }}"
      destroy: true
