name: dev env

on:
  pull_request:
    branches:
      - "main"

env:
  WORKSPACE: "${{ github.repository_id }}-${{ github.event.pull_request.number }}"

jobs:
  create:
    if: contains(github.event.pull_request.labels.*.name, 'dev-create')

    uses: ./.github/workflows/terraform.yml
    with:
      matrix: '["dev-env"]'
      workspace: "${{ github.repository_id }}-${{ github.event.pull_request.number }}"

  prepare:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'dev-create')

    outputs:
      infra_jobs: "${{ steps.jobs.outputs.infra_jobs }}"
      default_jobs: "${{ steps.jobs.outputs.default_jobs }}"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Find comment
        uses: peter-evans/find-comment@v3
        id: comment
        with:
          issue-number: "${{ github.event.pull_request.number }}"
          comment-author: github-actions[bot]
          body-includes: "## dev: ${{ env.WORKSPACE }}"

      - name: Add comment
        if: steps.comment.outputs.comment-id == null
        uses: peter-evans/create-or-update-comment@v3
        with:
          comment-id: "${{ steps.comment.outputs.comment-id }}"
          issue-number: "${{ github.event.pull_request.number }}"
          body: |
            ## dev: ${{ env.WORKSPACE }}
            Your instance is getting ready. Please wait.

            ### Variables
            ```shell
            export NOMAD_ADDR=http://hashi.${{ env.WORKSPACE }}.fluence.dev.io:4646
            export CONSUL_HTTP_ADDR=http://hashi.${{ env.WORKSPACE }}.fluence.dev:8500
            export LOKI_ADDR=http://loki.${{ env.WORKSPACE }}.fluence.dev
            ```
          edit-mode: replace

      - name: Create matrix with jobs
        id: jobs
        run: |
          # create matrix with jobs
          infra_jobs=$(find dev-env/jobs/infra/* -maxdepth 0 -type d  | jq -R . | jq -sc .)
          default_jobs=$(find dev-env/jobs/default/* -maxdepth 0 -type d  | jq -R . | jq -sc .)
          echo "infra_jobs=${infra_jobs}" >> $GITHUB_OUTPUT
          echo "default_jobs=${default_jobs}" >> $GITHUB_OUTPUT

  infra:
    needs:
      - create
      - prepare

    uses: ./.github/workflows/terraform.yml
    with:
      workspace: "${{ github.repository_id }}-${{ github.event.pull_request.number }}"
      matrix: "${{ needs.prepare.outputs.infra_jobs }}"

  default:
    needs:
      - create
      - prepare
      - infra

    uses: ./.github/workflows/terraform.yml
    with:
      workspace: "${{ github.repository_id }}-${{ github.event.pull_request.number }}"
      matrix: "${{ needs.prepare.outputs.default_jobs }}"

  ready:
    runs-on: ubuntu-latest
    needs:
      - infra
      - default

    steps:
      - name: Find comment
        uses: peter-evans/find-comment@v3
        id: comment
        with:
          issue-number: "${{ github.event.pull_request.number }}"
          comment-author: github-actions[bot]
          body-includes: "## dev: ${{ env.WORKSPACE }}"

      - name: Update comment
        uses: peter-evans/create-or-update-comment@v3
        with:
          comment-id: "${{ steps.comment.outputs.comment-id }}"
          issue-number: "${{ github.event.pull_request.number }}"
          body: |
            ## dev: ${{ env.WORKSPACE }}
            Your dev env is ready.

            Visit dev dashboard at https://dash.${{ env.WORKSPACE }}.fluence.dev

            ### IPC
            eth-api accessible through load-balancers is running at `https://ipc.${{ env.WORKSPACE }}.fluence.dev`
            Each ipc host is also running eth-api instance accessible at `http://ipc-<index>.${{ env.WORKSPACE }}.fluence.dev:8545`

            ## Services
            | name | address |
            | ---- | ------- |
            | postgres | `postgres.${{ env.WORKSPACE }}.fluence.dev:5433` |
            | webdav | `https://webdav.${{ env.WORKSPACE }}.fluence.dev` |

            ### Variables
            ```shell
            export NOMAD_ADDR=http://hashi.${{ env.WORKSPACE }}.fluence.dev.io:4646
            export CONSUL_HTTP_ADDR=http://hashi.${{ env.WORKSPACE }}.fluence.dev:8500
            export LOKI_ADDR=http://loki.${{ env.WORKSPACE }}.fluence.dev
            ```
          edit-mode: replace
